# NUMPY EGZERSİZLERİ

# Array oluşturma

#### Import numpy as np (Numpy ı yükleyin )

### ([1,2,3,4,5]) elemanlarından oluşan bir array tanımlayın

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([1, 2, 3, 4, 5])

### 0 lardan oluşan 4 satırlı 5 sütunlu bir array oluşturun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

### 7 lerden oluşan 3 satırlı  5 sütunlu bir array oluşturun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 7.,  7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.,  7.],
       [ 7.,  7.,  7.,  7.,  7.]])

### 10 dan başlayarak 70 e kadar 5 er artan bir array oluşturun ( arange( ) fonksiyonunu kullanın)

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

### 0 ile 5 arasında 15 tane aynı uzaklıkta elemanı olan bir array oluşturun( linspace( ) fonksiyonunu kullanın)

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([ 0.        ,  0.35714286,  0.71428571,  1.07142857,  1.42857143,
        1.78571429,  2.14285714,  2.5       ,  2.85714286,  3.21428571,
        3.57142857,  3.92857143,  4.28571429,  4.64285714,  5.        ])

### Normal dağılımda 3 satır 5 sütunlu bir array oluşturun ( random.randn( ) )

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 0.50996335, -0.40369843, -0.91596777, -0.20350774, -1.75239162],
       [-0.8227835 , -0.68026281,  0.24159962,  0.04663958, -0.2497482 ],
       [ 0.57097675, -0.3843778 , -1.24597028,  0.60148094, -0.59834052]])

### 5 elemanlı birim matris oluşturun ( eye( ) )

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### 0 dan 24 e kadar sayıların olduğu bir array oluşturun ve reshape() metodunu kullanarak 4 satır ve 6 sütunlu hale getirin.

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

### 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayıp en düşük ve en yüksek değerleri tespit edin.

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

[ 0.5942851   0.58631574  0.54288512  0.43322797  0.85883432  0.68765966
  0.29451965  0.06766839  0.81940478  0.64117334]
0.858834321853
0.0676683924991


# Numpy indeksleme ve iterasyon



### Rastgele 16 sayıdan oluşan ve 4 satır 4 sütunlu bir array oluşturun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 0.48880268,  0.16857365,  0.16996916,  0.91218194],
       [ 0.9433983 ,  0.11313239,  0.66364934,  0.15974578],
       [ 0.48768513,  0.59788676,  0.21667421,  0.17761038],
       [ 0.09795829,  0.67998686,  0.82571978,  0.68715134]])

### 2.satır daki tüm elemanları çekin

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 0.9433983 ,  0.11313239,  0.66364934,  0.15974578]])

### 4 üncü satır 4 üncü sütundaki sayıyı çekin

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

0.68715134034939174

### 4 üncü sütundaki bütün elemanları çekin

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([[ 0.91218194],
       [ 0.15974578],
       [ 0.17761038],
       [ 0.68715134]])

### For döngüsünü kullanarak oluşturduğunuz 16 sayıdan oluşan array in sayılarını alt alta flat() metodunu kullanarak yazdırın

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

0.488802679735
0.168573650955
0.16996915822
0.912181942492
0.943398301456
0.113132394171
0.663649343748
0.159745777232
0.487685134439
0.597886756923
0.216674205666
0.177610382955
0.0979582874017
0.679986864771
0.825719779735
0.687151340349


# Numpy işlemler

### 0 ile 1 arasında Rastgele 4 sayıdan oluşan bir array oluşturun ve her sayıyı 5 ile çarpın

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

array([ 3.59596072,  2.88977277,  3.23761792,  2.07067878])

### Oluşturduğunuz array in sayılarının toplamını bulun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

9.2846101377415025

### Oluşturduğunuz array in standart sapmasını bulun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

1.4977659819850548

### Oluşturduğunuz array in varyansını bulun

In [ ]:
ÇIKTILARIN KAYBOLMAMASI İÇİN KODUNUZU BURAYA YAZINIZ.

2.2433029367916557