In [1]:
## NUMPY CHEAT SHEET

In [ ]:
import numpy as np

# Numpy array

In [12]:
# create a simple list
a = [1,2,3]
type(a)


list

In [13]:
#create a numpy array 
b = np.array([1,2,3])
print(type(b))


<class 'numpy.ndarray'>


In [16]:
# create an 2x2 ndarray with float numbers
c = np.array([(3.2,4,5), (4,5,6)], dtype=float)
print(c)

[[3.2 4.  5. ]
 [4.  5.  6. ]]


In [22]:
# create an array of evenly
d =  np.arange(10,25,3)
print(d)


[10 13 16 19 22]


In [30]:
# Create an array of evenly
np.linspace(0,50,5) 


array([ 0. , 12.5, 25. , 37.5, 50. ])

In [31]:
#create an 3x4 array of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
# Create a constant array / full 7 filled 4x4 array
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [35]:
# create  a 2x2 identity matrix
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [39]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random


In [43]:
#create 4 array of random
np.random.randn(4)

array([-1.52832405,  0.37890197,  1.00337704,  0.413779  ])

In [44]:
np.random.randn(4,4)

array([[ 0.72552155, -0.45089236,  1.54779981,  1.78477729],
       [ 0.16201   ,  1.67907482,  0.14071199, -0.7375202 ],
       [-1.23076299, -1.17592868, -0.59251944, -0.60811365],
       [ 0.91354882, -0.03414402,  1.36078257, -1.94684653]])

In [46]:
np.random.randint(1,10)

8

In [49]:
np.random.randint(1,10,5)

array([8, 7, 4, 4, 1])

In [52]:
myNumpyArray = np.arange(20)
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# methods of numpy arrays


In [54]:
myNumpyArray.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [56]:
myNumpyArray.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
myNumpyArray.max()

19

In [58]:
myNumpyArray.min()

0

In [59]:
benimRandomDizim= np.random.randint(2,300,30)

In [60]:
benimRandomDizim

array([268, 151, 293, 100, 258,  81, 237, 181, 121, 211, 121, 293, 184,
       133,  96, 172, 146, 277,  58,   4, 220, 133, 107, 295,  55,  21,
       184,   2, 278, 180])

In [61]:
benimRandomDizim.min()

2

In [62]:
benimRandomDizim.max()

295

In [65]:
#en büyük eleman kaçıncı indexte??
benimRandomDizim.argmax()

23

In [66]:
myArray = np.arange(0,15)

In [67]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
myArray[5]

5

In [69]:
myArray[3:8]

array([3, 4, 5, 6, 7])

In [70]:
myArray[3:8] = -3

In [71]:
myArray

array([ 0,  1,  2, -3, -3, -3, -3, -3,  8,  9, 10, 11, 12, 13, 14])

In [72]:
otherArray = np.arange(0,20)

In [73]:
otherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
slicingArray = otherArray[5:11]  

In [75]:
slicingArray

array([ 5,  6,  7,  8,  9, 10])

In [76]:
slicingArray [:]

array([ 5,  6,  7,  8,  9, 10])

In [77]:
slicingArray[:] = 555

In [78]:
slicingArray

array([555, 555, 555, 555, 555, 555])

In [79]:
otherArray

array([  0,   1,   2,   3,   4, 555, 555, 555, 555, 555, 555,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

 # Matrix


In [88]:
myList = [[10,20,30],[30,40,50],[50,60,40]]
matrixA= np.array(myList)

In [89]:
matrixA

array([[10, 20, 30],
       [30, 40, 50],
       [50, 60, 40]])

In [92]:
matrixA[0]


array([10, 20, 30])

In [95]:
matrixA[1][2] 

50

In [96]:
matrixA[1,2]

50

In [97]:
matrixA[1:,2]

array([50, 40])

In [104]:
newList = [[1,2,3],[15,16,17],[20,25,30],[0,10,30]]

In [105]:
newMatrix= np.array(newList)

In [106]:
newMatrix

array([[ 1,  2,  3],
       [15, 16, 17],
       [20, 25, 30],
       [ 0, 10, 30]])

In [107]:
newMatrix[[3,2]]

array([[ 0, 10, 30],
       [20, 25, 30]])

# Operations


In [111]:
array1 = np.random.randint(5,100,20)

In [112]:
array1

array([25, 68, 11, 92, 19, 23, 68, 57, 55, 83, 80, 47, 22, 21, 58, 51, 58,
       95, 73, 21])

In [114]:
array1 > 25

array([False,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False])

In [116]:
filteredArray = array1 >25

In [117]:
filteredArray

array([False,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False])

In [118]:
array1[filteredArray]

array([68, 92, 68, 57, 55, 83, 80, 47, 58, 51, 58, 95, 73])

In [119]:
array1[array1>25]

array([68, 92, 68, 57, 55, 83, 80, 47, 58, 51, 58, 95, 73])

In [120]:
lastArray = np.arange(0,25)

In [121]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [122]:
lastArray+lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [123]:
lastArray-lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [124]:
np.sqrt(lastArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [125]:
np.max(lastArray)

24